disabled_rules:
    - opening_brace
    - control_statement
    - function_body_length
    - switch_case_alignment
    - statement_position
    - trailing_comma

type_name:
    max_length:
        warning: 60
        error: 60
    excluded:
        - devbanApp

nesting:
    type_level:
        warning: 2
